
# This is your Supabase configuration file
# For local development, the local project is used automatically
# For production, the production project is used

# Local development project ID
project_id = "uhudxpdzeddkqebgeqjn"

# Production project ID (used when deployed to production environment)
# production_project_id = "cklbbxfegppikhusrvzm"

[functions.send-contact-email]
verify_jwt = false